print('-----------------------------Пипсы----------------------------------------')
print('vvedite slovosochetaine (можно и по русски)')
s=input()
k=s.find(' ')
print(s[k+1]+s[1:k]+s[k]+s[0]+s[k+2:])
